### ISSUE TITLE
Tagsinput Text Field Max Length

### ISSUE THREAD

**Issue by joshuajameshunt** [bootstrap-tagsinput/bootstrap-tagsinput#361]
Great plugin! The only issue I noticed was that the text field seems to default (with !important no less) to 3em in the absence of a placeholder. This causes even a reasonable length tag to overfill the box. My recommendation would be either to 1) make the default size a bit larger or 2) dynamically resize the box based on content length.

**Comment by methodbox** [comment]
I reported the same issue on a fork of this for Meteor.  Unfortunately, the problem resides in a poorly written part of the script where the ```style= ...!important``` is forced.  This makes it impossible to override, particularly in Meteor when the template is rendered.

The problem comes from this part of the script:

```
... this.$input.get(0).style.cssText="width: "+d+" !important;",this.build(c)} ...
```

The script works by actually hiding the ``` input``` element that you create and replacing it with one rendered by the script.  There absolutely should not be any styling forced at the time of rendering, much less using ```!important```.

The styles should only be inherited.

**Comment by lucknerjb** [comment]
A consideration would be to grab the length of the input we are hiding and use that instead of applying a non-sensible default.

Resizing the input is something I've been wanting to explore for a while now so that the tag stays visible as the user types... might not be for this initial change but it's an possible future option.
