### ISSUE TITLE
how change delimeter

### ISSUE THREAD

**Issue by jamiya** [bootstrap-tagsinput/bootstrap-tagsinput#374]
Hello this plugin very helpful. But change delimeter character not available. How change comma with semiclone ?

**Comment by sakalauskas** [comment]
Hi,

I was looking as well into this issue, though, I needed to change to pipe character (|) instead of comma.

You can simply modify bootstrap-tagsinput.js line 87:

var items = item.split(',');

and change to your desired character, so in your case

var items = item.split(;');


And don't forget to add confirm key code, which for semicolon according to [this](http://keycodes.atjayjo.com/) is 186

Cheers,

**Comment by jamiya** [comment]
Thanks @sakalauskas for your help. I've tried this solution. 
But it does'nt works.

**Comment by lucknerjb** [comment]
Will be fixed with #397
