### ISSUE TITLE
tag text appears when typeahead input looses focus

### ISSUE THREAD

**Issue by joekeen** [bootstrap-tagsinput/bootstrap-tagsinput#386]
Using the Typeahead example: when creating a tag not returned by typeahead's source (default: true), when the input looses focus - the tag text appears as un-styled text next to the new tag.

Refer screenshot:

![screen shot 2015-08-25 at 9 24 43 pm](https://cloud.githubusercontent.com/assets/1745655/9465564/03f0cf7a-4b71-11e5-98e3-6a3a75ef3f4f.png)

**Comment by weaverryan** [comment]
+1 for this - it's hopefully easy to debug, since as @joekeen shows, you can see this on the demo: just type "Cape" to see the "Cape Town" autocomplete, but then hit "tab" without selecting the item. You should see "Cape Town" written as text into the box (though you may not see it without moving your cursor around, as the text box remains small).

Thanks!

**Comment by sgaynetdinov** [comment]
+1
i'm used
```javascript
var $input = $('.typeahead');
$input.change(function(){
            $(".bootstrap-tagsinput input")[0].value = '';
});
```

**Comment by mjau-mjau** [comment]
+1
For me, the problem was only when I input values that ARE in the typeahead source. Thanks to @sgaynetdinov , I solved it with the following:

```javascript
$('.bootstrap-tagsinput').change(function(){
  $(this).find('input').val('');
});
```

**Comment by lucknerjb** [comment]
Moving issue to release 0.7.1
