### ISSUE TITLE
minLength for typeahead

### ISSUE THREAD

**Issue by popovae** [bootstrap-tagsinput/bootstrap-tagsinput#478]
Hello,
minLength for typeahead is not working with 0 value....
https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/314 states the following example:

`$(element).tagsinput({
  typeaheadjs: [
      {
         minLength: 4
      },
      {
       name: 'citynames',
       displayKey: 'name',
       valueKey: 'name',
       source: citynames.ttAdapter()
     }
  ]
});`

`minLength: 0` - returns results only after at least 1 symbol is entered.

**Comment by lucknerjb** [comment]
In this scenario, do you expect it to show all the results as soon as the input gets focus? Just want to make sure that I am following properly...

**Comment by danvim** [comment]
@lucknerjb It should show all results upon click or focus on the input.

**Comment by joselherg** [comment]
@lucknerjb @popovae @danvim same problem for me; users do not know what options are available (and change from time to time), so I need to show all options available before start typing.

**Comment by lucknerjb** [comment]
@joselherg @danvim This is a little late but here is a working example basically.

https://jsfiddle.net/czqezjax/

It took me a while to figure it out but you need to do more than just set the `minLength` option with the plugin. You also need to handle the scenario where you have a zero-length query (which is what happens when you focus on the element) via typeahead.

Hope this helps!

**Comment by danvim** [comment]
@lucknerjb That definitely helped! I was actually waiting for a fix while I work on something else!

However, the fact that `minLength:0` doesn't automatically show the query in the plugin should be an unwanted behavior, because on the demo page of twitter typeahead: https://twitter.github.io/typeahead.js/examples/#default-suggestions , "Default Suggestions" is one of the intended behaviors.

Therefore, I think the code should be best incorporated into the plugin's js fie. :)

**Comment by danvim** [comment]
@lucknerjb Thanks, that definitely helped! I can't believe I didn't look again at the typeahead demos. Hahaha.
