### ISSUE TITLE
Tags vulnerable to xss

### ISSUE THREAD

**Issue by masonnl** [bootstrap-tagsinput/bootstrap-tagsinput#479]
Our team recently ran into a problem. We had assumed that this library would escape tags to prevent javascripts from being injected and executed by nefarious clients. We managed to work around this with the way we handle our forms in general, BUT this seems like a bad thing imvho.

ie - place this in the tag field on the [example page](http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)

``` html
<script>alert('boom!');</script>
```

My question then, is do you allow `script` tags to be executed for any particular reason? Is it an oversight? Are there technical reasons that I'm not understanding?

**Comment by cdvv7788** [comment]
You should not render unescaped user content, but that is responsibility of the server. It would be nice if the plugin could escape tags, but not a requirement for it to do what it intends to do (imho).

**Comment by lucknerjb** [comment]
I agree with @cdvv7788 ... I'm not sure this falls under the responsibility of the plugin. Things like escaping double-quotes (#485) make sense because that's broken functionality. Escaping user content to prevent XSS and other possible attacks, that, I think, should be handled by the developers.

That being said... the plugin could provide some **basic** escaping and leave the rest up to the devs to handle. Something along the lines of this:

https://github.com/janl/mustache.js/blob/master/mustache.js#L60

```
  var entityMap = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
    '/': '&#x2F;',
    '`': '&#x60;',
    '=': '&#x3D;'
  };

  function escapeHtml (string) {
    return String(string).replace(/[&<>"'`=\/]/g, function fromEntityMap (s) {
      return entityMap[s];
    });
  }
```

**Comment by masonnl** [comment]
Thanks for the input @lucknerjb @cdvv7788. I wanted to bring up the conversation just in case. If there are no more quandaries, I will close out this issue.

**Comment by danez** [comment]
This is also reported here: https://nodesecurity.io/advisories/124 and in #501
