### ISSUE TITLE
Doesn't recognize comma input on Android devices

### ISSUE THREAD

**Issue by dleffler** [bootstrap-tagsinput/bootstrap-tagsinput#480]
When using an Android device and Chrome, the 'comma' is not recognized as the delimiter for a tag.  I've connected remote debugging and when entering the input on the windows pc it works, but on the Android device it doesn't.

**Comment by ipsoftware** [comment]
yuuup :) is not recognized comma, space and others :(

**Comment by lucknerjb** [comment]
Hmmm, well this will be a fun one to debug. Have you been able to grab the charcode that gets sent when using a comma on an Android device?

**Comment by ipsoftware** [comment]
is 44 :(

**Comment by lucknerjb** [comment]
Hmmm, weird. That's the right charcode for the comma key. I'll have a look at it tonight or tomorrow once I get a free cycle and use the debugger to try and figure out what is going on. Thanks for confiming the charCode!

**Comment by dleffler** [comment]
With my troubleshooting, the issue seems to be with Android 'keypress' event being deprecated in favor of 'keydown' or 'keyup'?

**Comment by RandomDude777** [comment]
After some testing it seems that keypresed wont fire on android. Once it's fired with keydown it returns 229 as the charCode for all keys using jquery's method. However, after trying a javascript EventListener everything seemed to be normal...

**Comment by RandomDude777** [comment]
As a temporary fix to this issue I've changed all keypress events to keyup events and from edited lines

469 from:
`
var text = $input.val(),
`

to:

`
var text = $input.val(),
maxLengthReached = self.options.maxChars && text.length >= self.options.maxChars;

var character = text.slice(-1);
var code = character.charCodeAt(0);
event.which = code;
`

Tested working on current and past 3 Android updates. (I know its hacky and not clean but this bug is also quite annoying and wanted a temp fix)

**Comment by rubenlpz** [comment]
Hi @RandomDude777, it doesn't work for me (switching to keyup in bootstrap-tagsinput.js).  The "," separator is not recognized in android, until the input lost focus.

**Comment by rubenlpz** [comment]
Finally, it works! I had forgot to change the keypress to keyup events and update the minified version (min.js).  Good workaround @RandomDude777

**Comment by renebrain** [comment]
I've fixed this thing in the actual code, since i haven't found it here, if anyone wants to push it here on github it would be cool, since i have no idea how it works here
line 425
`self.$container.on('keyup', 'input', $.proxy(function(event) {`

line 442
`if (self.options.cancelConfirmKeysOnEmpty === false || keyCombinationInList(event, self.options.confirmKeys)) {
                        event.preventDefault();
                    }`

line 620
`var key = keyPressEvent.which || keyPressEvent.keyCode;
            if(!key || key == 229){
                var ss = keyPressEvent.target.selectionStart -1;
                var ssv = ss || 0;
                var char = keyPressEvent.target.value.substr(ssv,1);
                key = char.charCodeAt(0);
            }
            if (typeof (keyCombination) === 'number' && key === keyCombination) {
                found = true;
                return false;
            }`

line 631
`if (key === keyCombination.which) {`

**Comment by DushyantDhundara** [comment]
@renebrain I tried to put the edits you suggested, now the comma works in mobile, but it stopped working in the web. I can't figure out what I am doing wrong. Would you be kind enough to provide the version of js with this edit so the comma delimiter works on both android and web? 
Thanks a lot.

**Comment by PermanAtayev** [comment]
I wonder if this issue was resolved
