### ISSUE TITLE
Is this Repo a Joke?!

### ISSUE THREAD

**Issue by r3verser** [bootstrap-tagsinput/bootstrap-tagsinput#585]
Realy, why when i got "1","=","1" in my tags, output function gives me - ["1","="] ?
Why when i have duplicated tags (official feature) like 1 and 1, removing any of them removes them all?
Why when typing tags in order - "xxx","=","1","1" in output i have - ["1","=","xxx"] ?
Are you hacking kidding me? Why that stuff has >2,200 stars on github omg? :angry:

**Comment by BasicWolf** [comment]
Why not fix the issue and contribute it to all the users? If still in rage, read the license more carefully, is explicitly states that

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
> IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
> FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

**Comment by r3verser** [comment]
I'm not agree with your vision of situation, but appreciate your sensible response. Sounds really calm, isn't it? :smoking:

**Comment by johnmcconnell** [comment]
A better question is this repo still active? Last update was in October

**Comment by ryantheleach** [comment]
Worse yet, you can't view forks.

**Comment by mecca66** [comment]
Repo is not a joke. The plugin works really well, just follow the instructions. The project doesn't look like it's being supported any more so if you have an issue you can either go to stack overflow, fix it yourself or find something else to use instead of complaining. Have a bit of respect for the guys who initially created the plugin instead of moaning, we're all developers at the end of the day and as a community we rely on each other for support, if you don't understand that then you're in the wrong game...
