### ISSUE TITLE
knockout and refresh doesn't work

### ISSUE THREAD

**Issue by dctdct** [bootstrap-tagsinput/bootstrap-tagsinput#98]
Hi,

thanks for the awesome plugin! I noticed one small issue.

My html contains a input field bound to a view model property called "inputTags".
    <div class="form-group">
        <input id="input-tags" class="form-control" data-role="tagsinput" data-bind="value: inputTags" />
    </div>

inputTags property is a observable. 
this.inputTags = ko.observable('');

When updating inputTags inside the view model nothing happens to the tagsinput control. I also tried to call refresh:

this.inputTags(newtags); // vm property update
$('#input-tags').tagsinput('refresh'); // refresh ui but nothing happens

My workaround right now is to remove all tags from the control and call the add method:

$('#input-tags').tagsinput('removeAll');
$('#input-tags').tagsinput('add', newtags);

Take care,
dct

**Comment by simo163** [comment]
@dctdct did you arrive to solve it? I am trying also to delete all and add new tags but does not work.

**Comment by ghiscoding** [comment]
Was there any improvement on this? 

The workaround does work but is far from ideal

**Comment by angeloreale** [comment]
I just did:

$('#input-tags').tagsinput('destroy');
$('#input-tags').tagsinput();

This worked without having to add and remove tags.

**Comment by cosminbosutar** [comment]
I has a very similar problem. I us jquery to display ajax extracted data in a modal. Each time the modal in opened I need to extract the relevant data and dynamically populate the tagsinput.

When the first modal was opened everything was fine but starting from the second modal the tagsinput was not refreshed and the new tags were just appended despite removeAll being called. This is the commands order I used to get the above described behavior:
```
modal.find('#t_skills').tagsinput('removeAll');
modal.find('#t_skills').tagsinput('refresh');
modal.find('#t_skills').tagsinput('add', response.technical_skills);
```

The fix for this was to change the plugin and rewrite the removeAll method like this:
```
removeAll: function() {
  var self = this;

  $('.tag', self.$container).remove();
  $('option', self.$element).remove();

  while(self.itemsArray.length > 0){
    var tag = self.itemsArray.pop();
      self.remove(tag, );
    }

    self.pushVal();
}
```

**Comment by edl-paulpiedad** [comment]
call the container instead
ex: <div class="bootstrap-tagsinput"></div>
answer:
$('.bootstrap-tagsinput').tagsinput('refresh');

You can use the method 'refresh' already if you call the div container and not the id/class of input.
